languageCode = "id-ID"
categories = "category"
tags = "tag"
theme = "farmite"

[languages]
    [languages.id]
        contentDir = "content/indonesia"
        baseURL = ""
        weight = 1
    [languages.en]
        contentDir = "content/english"
        baseURL = ""
        weight = 2