languageCode = "id-ID"
categories = "category"
tags = "tag"
theme = "farmite"

[languages]
    [languages.id]
        contentDir = "content/indonesia"
        baseURL = "/dev/id/"
        weight = 2
    [languages.en]
        contentDir = "content/english"
        baseURL = "/dev/en/"
        weight = 1