languageCode = "id-ID"
categories = "category"
tags = "tag"
theme = "farmite"

[languages]
    [languages.id]
        contentDir = "content/indonesia"
        baseURL = "https://saputra.co.id/id"
        weight = 2
    [languages.en]
        contentDir = "content/english"
        baseURL = "https://saputra.co.id"
        weight = 1